import scanpy as sc
print("Loading PBMC3k")
adata = sc.datasets.pbmc3k()
adata.var_names_make_unique()
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata, n_top_genes=1000)
print("PCA with randomized")
sc.tl.pca(adata, svd_solver='randomized', n_comps=20)
print("Neighbors")
sc.pp.neighbors(adata, n_neighbors=15, n_pcs=20)
print("UMAP")
sc.tl.umap(adata)
print("Done!")
